//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAplication20200918_2 {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Libai {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Libai() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsAplication20200918_2.Libai", typeof(Libai).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 李白 {
            get {
                object obj = ResourceManager.GetObject("李白", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 龙马花雪毛，金鞍五陵豪。
        ///秋霜切玉剑，落日明珠袍。
        ///斗鸡事万乘，轩盖一何高。
        ///弓摧南山虎，手接太行猱。
        ///酒后竞风采，三杯弄宝刀。
        ///杀人如剪草，剧孟同游遨。
        ///发愤去函谷，从军向临洮。
        ///叱咤经百战，匈奴尽奔逃。
        ///归来使酒气，未肯拜萧曹。
        ///羞入原宪室，荒淫隐蓬蒿。 的本地化字符串。
        /// </summary>
        internal static string 白马篇 {
            get {
                return ResourceManager.GetString("白马篇", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 噫吁嚱，危乎高哉！
        ///蜀道之难，难于上青天！
        ///蚕丛及鱼凫，开国何茫然！
        ///尔来四万八千岁，不与秦塞通人烟。
        ///西当太白有鸟道，可以横绝峨眉巅。
        ///地崩山摧壮士死，然后天梯石栈相钩连。
        ///上有六龙回日之高标，下有冲波逆折之回川。
        ///黄鹤之飞尚不得过，猿猱欲度愁攀援。
        ///青泥何盘盘，百步九折萦岩峦。
        ///扪参历井仰胁息，以手抚膺坐长叹。
        ///问君西游何时还？畏途巉岩不可攀。
        ///但见悲鸟号古木，雄飞雌从绕林间。
        ///又闻子规啼夜月，愁空山。
        ///蜀道之难，难于上青天，使人听此凋朱颜！
        ///连峰去天不盈尺，枯松倒挂倚绝壁。
        ///飞湍瀑流争喧豗，砯崖转石万壑雷。
        ///其险也如此，嗟尔远道之人胡为乎来哉！
        ///剑阁峥嵘而崔嵬，一夫当关，万夫莫开。
        ///所守或匪亲，化为狼与豺。
        ///朝避猛虎，夕避长蛇；磨牙吮血，杀人如麻。
        ///锦城虽云乐，不如早还家。
        ///蜀道之难，难于上青天，侧身西望长咨嗟！ 的本地化字符串。
        /// </summary>
        internal static string 蜀道难 {
            get {
                return ResourceManager.GetString("蜀道难", resourceCulture);
            }
        }
    }
}
